### ISSUE TITLE
making indices and merging are slower than MapReduce ingestion

### ISSUE THREAD

**Issue by jason-heo** [metamx/druid-spark-batch#115]
Hi,

I've read the post about stop supporting this project. But could you please answer this question if you have some time?

My team has implemented supporting parquet files. It' almost done! But the problem is that ingest speed is 3 times slower than MaReduce ingestion.

It turned out that the slower point is creating IncrementalIndex and merge them.

https://github.com/metamx/druid-spark-batch/blob/master/src/main/scala/io/druid/indexer/spark/SparkDruidIndexer.scala#L293

```
    ...
    val indices: util.List[IndexableAdapter] = groupedRows.map(rs => {
      // TODO: rewrite this without using IncrementalIndex, because IncrementalIndex bears a lot of overhead
      // to support concurrent querying, that is not needed in Spark
      val incrementalIndex = new IncrementalIndex.Builder()

      ...
    }

    val file = finalStaticIndexer.merge(indices, ...)
```

There is a comment like this:

>       // TODO: rewrite this without using IncrementalIndex, because IncrementalIndex bears a lot of overhead

- Question1: Can I know what this `TODO` means?
- Question2: [`IndexGeneratorJob.reduce`](https://github.com/druid-io/druid/blob/master/indexing-hadoop/src/main/java/io/druid/indexer/IndexGeneratorJob.java#L585) is also using `IncrementalIndex` as well. I checked MapReduce and Spark Ingest implementation, and It's the same. Could you advise what should I check?

Thanks.

**Comment by leventov** [comment]
Conceptually, `IncrementalIndex` supports event-at-a-time data aggregation during long periods of time, with unknown total number of events, and supports concurrent queries, which should work semantically the same as queries over historical Druid segments, at any moment.

This is not needed during index creation in Spark or Hadoop, because 1) we know all data that is going to be comprised in a segment from the beginning (hence we could allocate some data structures of the right size from the beginning, etc.) Also we could know all dimensions and metrics in the data from the beginning. 2) We don't need to support concurrent querying while the index is prepared.

The way to change the code is to implement [`IndexableAdapter`](https://github.com/druid-io/druid/blob/a9d8539802fc570eff07ece7eef71817d4c62d7b/processing/src/main/java/io/druid/segment/IndexableAdapter.java) right in the Spark or Hadoop indexing code, and provide it directly to one of the methods in `IndexMergerV9` to produce a segment, thus skipping intermediate `IncrementalIndex` creation.

**Comment by jason-heo** [comment]
@leventov 

Thank you for your kind answer.
